
import { Poppins } from "next/font/google";
import 'react-responsive-modal/styles.css';
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers  from "./providers";
import DevToolsBlocker from "./devtoolsBlocker";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata = {
  title: "Respyr Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >

    <Providers>
          <div 
          className="">
 {/* <DevToolsBlocker /> */}
            {children}
          </div>

          <div className="fixed top-4 right-4 z-50">
            <Toaster position="top-right"/>
          </div>
    </Providers>
      </body>
    </html>
  );
}
